eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
    port: 8080
spring:
    datasource:
        password: ''
        url: jdbc:h2:mem:testdb
        username: saf
    h2:
        console:
            enabled: true
            path: /h2-console
    output:
        ansi:
            enabled: ALWAYS
test:
    config: My config value test profile update
